development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:00bb4bec43299efe3e2217bdb56180e1@hammerjaw.redistogo.com:9037/
  channel_prefix: message_me_production
